#!/usr/bin/env bash
#transfer files

if [[ $# -lt 3 ]]; 
    then
        echo "Usage: 0-transfer_file Path_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

file="$1"
ip="$2"
username="$3"
ssh="$4"

if [[ $# -ge 4 ]];
then
	scp -o StrictHostKeyChecking=no -i "$ssh" "$file" "$username"@"$ip":~/
else
	scp -o StrictHostKeyChecking=no "$file" "$username"@"$ip":~/
fi
