#!/usr/bin/env bash
#transfer files

if [[ $# -ne 4 ]];
    then
        echo "Usage: 0-transfer_file Path_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

file=$1
ip=$2
username=$3
ssh=$4

scp -i "$ssh" "$file" "$username"@"$ip":~/
