#!/usr/bin/env bash
#install nginx

apt-get update
apt-get -y install nginx 
ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/index.html
if [ "$(pgrep -c nginx)" -le 0 ]
then
    sudo service nginx start
else
    sudo service nginx restart
fi
