#!/usr/bin/env bash
#install nginx

apt-get update
apt-get -y install nginx 
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo chmod -R 777 /var/www
sudo echo 'Hello World!' > /var/www/html/index.html

newconfig=\
"server {                                                                                listen 80 default_server;                                                                                                                        
        listen [::]:80 default_server;                                                                                                                                                                                                                        
        root /var/www/html;                                                                                                                              
        # Add index.php to the list if you are using PHP                                                                                                 
        index index.html index.htm index.nginx-debian.html;                                                                                              
                                                                                                                                                         
        server_name www.mogedi.tech;                                                                                                                     
                                                                                                                                                         
        location / {                                                                                                                                     
                try_files $uri $uri/ =404;                                                                                                               
        }   
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}
"
sudo echo "$newconfig" > /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]
then
    sudo service nginx start
else
    sudo service nginx restart
fi
