#!/usr/bin/env bash
# display infinity and beyond while sleeping for 2 sec am receiving when receiving a sigterm signal

msg()
{
	echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
     echo "To infinity and beyond"
     sleep 2
done
